import click, json, re
from fluvel.core.tools import load_style_sheet
from fluvel.controllers.ContentHandler import ContentHandler
from fluvel.utils.paths import CONTENT_DIR, PROD_CONTENT_DIR, THEMES_DIR, PROD_THEMES_DIR, APP_ROOT
from fluvel.core.exceptions.expect_handler import expect

# CLI tools
from fluvel.cli.tools.ClickStyledMessage import echo

@click.command
def build() -> None:
    """
    Builds the application for production mode.

    This command performs three main tasks:
    
    1. Compiles dynamic content (menus, static text) into optimized JSON files 
       for each language.
    2. Consolidates multi-file QSS themes into single, optimized QSS files.
    3. Switches the application's configuration from development mode to
       production mode by modifying the ``DEV_MODE`` key in ``config.toml``.
    """
    
    generate_json_files()
    generate_themes()
    change_dev_mode()
    
    echo(
        ":yellow[LOG: THE] " \
        ":blue['DEV_MODE'] " \
        ":yellow[KEY IN THE] " \
        ":blue['config.toml'] " \
        ":yellow[FILE WAS MODIFIED TO RUN THE APPLICATION WITH THE OPTIMIZED FILES.]"
    )

@expect.IOError()
def generate_json_files() -> None:
    """
    Generates optimized JSON files for static content and menus.

    It iterates through all language folders in the development content directory
    and uses :py:class:`fluvel.controllers.ContentHandler` to compile the
    dynamic content into two static JSON files per language in the
    production content directory:

    - ``menus/menus.json``: Contains all menu definitions.
    - ``<lang>.json``: Contains all static textual content.

    This optimization speeds up content loading in production mode.

    :raises IOError: If there are issues creating directories or writing files.
    """

    for lang in CONTENT_DIR.iterdir():

        prod_lang_dir = PROD_CONTENT_DIR / lang.name
        prod_lang_dir.mkdir(parents=True, exist_ok=True)

        menus_folder = prod_lang_dir / "menus"
        menus_folder.mkdir(parents=True, exist_ok=True)

        ContentHandler.load_content("development", lang.name)

        menus_json = menus_folder / "menus.json"
        content_json = prod_lang_dir / f"{lang.name}.json"

        with open(menus_json, "w", encoding="utf-8") as f:
            json.dump(ContentHandler.MENU_CONTENT, f, indent=4, ensure_ascii=False)

        with open(content_json, "w", encoding="utf-8") as f:
            json.dump(ContentHandler.STATIC_CONTENT, f, indent=4, ensure_ascii=False)

        echo(f":green[LANG:] :blue[{lang.name}] successfully optimized.")

@expect.IOError()
def generate_themes() -> None:
    """
    Consolidates QSS theme files into single production files.

    It iterates through all theme folders in the development themes directory. 
    For each theme, it recursively finds all ``.qss`` files, concatenates their 
    content using :py:func:`fluvel.core.tools.load_style_sheet`, and writes the 
    result to a single ``<theme_name>.qss`` file in the production themes 
    directory.

    :raises IOError: If there are issues creating directories or writing files.
    """

    PROD_THEMES_DIR.mkdir(parents=True, exist_ok=True)

    for theme in THEMES_DIR.iterdir():

        theme_file = PROD_THEMES_DIR / f"{theme.name}.qss"
        
        # List of .qss files
        qss_files: list = theme.rglob("*.qss")

        # Content to be loaded to the ui
        qss_content: str = ""

        # Iterating and concatenating QSS content from files
        for qss_file in qss_files:
            qss_content += load_style_sheet(qss_file)

        with open(theme_file, "w", encoding="utf-8") as f:
            f.write(qss_content)

        echo(f":green[THEME:] adding :blue[{theme.name}]")

@expect.IOError()
def change_dev_mode() -> None:
    """
    Updates the 'DEV_MODE' setting in config.toml to false.

    This function reads the main ``config.toml`` file, uses a regular expression 
    to find and replace the value associated with the ``DEV_MODE`` key, setting it 
    to ``false``. This ensures the application runs using the optimized production 
    files generated by :py:func:`generate_json_files` and :py:func:`generate_themes`.

    :raises IOError: If there are issues reading or writing the configuration file.
    """

    config_file_path = APP_ROOT / "config.toml"

    # Ensures the file exists before attempting to read it
    if not config_file_path.exists():
        click.echo(f"Error: The configuration file was not found in {config_file_path}")
        return
        
    # Reads the file content
    content_str = config_file_path.read_text(encoding="utf-8") 

    pattern = r"(\bDEV_MODE\s*=\s*)([a-z]+)(\s*\n)"
    replace_str = r"\g<1>false\g<3>"

    changed_content = re.sub(pattern, replace_str, content_str, count=1, flags=re.IGNORECASE)

    # Writes all the modified content at once
    config_file_path.write_text(changed_content, encoding="utf-8")