import click
import re
from typing import List, Tuple

class ClickStyledMessage:
    """
    A utility class for printing messages to the console using the 
    :func:`click.echo` function and applying foreground color styles 
    using simple markup syntax.

    The markup syntax uses the pattern ``:color_name[text]``, 
    where ``color_name`` is a color supported by Click.

    :ivar regex: The compiled regular expression used to find 
                 and replace the style pattern in the message.
    :vartype regex: str
    """

    regex = r":([a-z_]+)\[(.*?)\]"

    @classmethod
    def _style_replacer(cls, match: re.Match) -> str:
        """
        Replacement function used by :func:`re.sub` to apply 
        the Click style to the matching text.

        :param match: The regular expression match object.
        :type match: re.Match
        :returns: The styled string generated by :func:`click.style`.
        :rtype: str
        """
        fg_color = match.group(1)
        text_content = match.group(2)
        
        return click.style(text=text_content, fg=fg_color)

    @classmethod
    def echo(cls, message: str) -> None:
        """
        Prints a message and a new line to standard output or a file,
        applying Click styles for the foreground colors defined
        in the message using the syntax ``:color_name[text]``.

        The supported color names are the same as those in :func:`click.style`:

        * ``black`` (might be a gray)
        * ``red``
        * ``green``
        * ``yellow`` (might be an orange)
        * ``blue``
        * ``magenta``
        * ``cyan``
        * ``white`` (might be light gray)
        * ``bright_black``
        * ``bright_red``
        * ``bright_green``
        * ``bright_yellow``
        * ``bright_blue``
        * ``bright_magenta``
        * ``bright_cyan``
        * ``bright_white``
        * ``reset`` (only resets the color code)

        :param message: The message to print, potentially containing style markers.
        :type message: str

        :returns: Nothing (prints directly to standard output).
        :rtype: None
        """

        full_message = re.sub(cls.regex, cls._style_replacer, message)
        click.echo(full_message)

    @classmethod
    def replace_with_style(
        cls, 
        text: str, 
        replacements: List[Tuple[str, str, bool]]
    ) -> str:
        """
        Applies Click styles to specific substrings within a larger text block 
        (like an ASCII tree structure).

        This is highly useful for applying consistent styling to fixed characters
        (like tree lines: ├───, └───, │) without relying on complex regex.

        :param text: The original text block.
        :type text: str
        :param replacements: A list of tuples, where each tuple contains:
                             (original_substring, click_color_name, bold_status)
        :type replacements: List[Tuple[str, str, bool]]
        :returns: The modified text with styles applied.
        :rtype: str
        
        Example
        -------
        .. code-block:: python

            tree_text = "root:\n├──A\n└──B"
            styled_text = ClickStyledMessage.replace_substring_style(
                tree_text,
                [
                    ("├──", "blue", False),
                    ("root:", "blue", True)
                ]
            )
        """
        for original, color, bold in replacements:
            
            # Replace the original substring with the stylized version of click.
            styled_replacement = click.style(original, fg=color, bold=bold)
            text = text.replace(original, styled_replacement)
            
        return text

def echo(msg: str) -> None:
    """
    Convenience function that calls ClickStyledMessage.echo()
    to print a message with inline style markup.

    The supported color names are the same as those in :func:`click.style`:

    * ``black`` (might be a gray)
    * ``red``
    * ``green``
    * ``yellow`` (might be an orange)
    * ``blue``
    * ``magenta``
    * ``cyan``
    * ``white`` (might be light gray)
    * ``bright_black``
    * ``bright_red``
    * ``bright_green``
    * ``bright_yellow``
    * ``bright_blue``
    * ``bright_magenta``
    * ``bright_cyan``
    * ``bright_white``
    * ``reset`` (only resets the color code)

    :param msg: The message to print, potentially containing style markers 
                (e.g., ":red[Error]").
    :type msg: str
    :returns: None
    :rtype: None
    """

    ClickStyledMessage.echo(msg)