# Copyright (C) 2025-2026 J. F. Escobar
# SPDX-License-Identifier: LGPL-3.0-or-later

import re
from dataclasses import dataclass

import click

COLORS: set[str] = {
    "black",
    "red",
    "green",
    "yellow",
    "blue",
    "magenta",
    "cyan",
    "white",
    "bright_black",
    "bright_red",
    "bright_green",
    "bright_yellow",
    "bright_blue",
    "bright_magenta",
    "bright_cyan",
    "bright_white",
    "reset",
}


@dataclass(slots=True)
class Modifier:
    color: str
    is_bold: bool


class ClickStyled:
    """
    A utility class for printing messages to the console using the
    :func:`click.echo` function and applying foreground color styles
    using simple markup syntax.

    The markup syntax uses the pattern ``[color](text)``,
    where ``color`` is a color supported by Click.

    :ivar regex: The compiled regular expression used to find
                 and replace the style pattern in the message.
    :vartype regex: str
    """

    regex = r"\[([a-z_!+]+)\]\(([^)]*)\)"

    @classmethod
    def _style_replacer(cls, match: re.Match) -> str:
        """
        Replacement function used by :func:`re.sub` to apply
        the Click style to the matching text.

        :param match: The regular expression match object.
        :type match: re.Match
        :returns: The styled string generated by :func:`click.style`.
        :rtype: str
        """
        raw_style = match.group(1)
        text_content = match.group(2)

        modifier = cls._apply_modifiers(raw_style)

        if modifier.color not in COLORS:
            return match.group(0)

        return click.style(text=text_content, fg=modifier.color, bold=modifier.is_bold)

    @classmethod
    def _apply_modifiers(cls, raw_style: str) -> Modifier:
        # Modifier
        is_bold = "!" in raw_style
        is_bright = "+" in raw_style

        # Reset color
        color_name = raw_style.replace("!", "").replace("+", "")

        if is_bright and not color_name.startswith("bright_"):
            color_name = f"bright_{color_name}"

        return Modifier(color=color_name, is_bold=is_bold)

    @classmethod
    def process(cls, message: str) -> str:
        """
        Apply Click styles for the foreground colors defined
        in the message using the syntax ``[color](text)``.

        The supported color names are the same as those in :func:`click.style`:

        * ``black`` (might be a gray)
        * ``red``
        * ``green``
        * ``yellow`` (might be an orange)
        * ``blue``
        * ``magenta``
        * ``cyan``
        * ``white`` (might be light gray)
        * ``bright_black``
        * ``bright_red``
        * ``bright_green``
        * ``bright_yellow``
        * ``bright_blue``
        * ``bright_magenta``
        * ``bright_cyan``
        * ``bright_white``
        * ``reset`` (only resets the color code)

        :param message: The message to print, potentially containing style markers.
        :type message: str

        :returns: The final message completely stylized.
        :rtype: str
        """

        full_message = re.sub(cls.regex, cls._style_replacer, message)

        return full_message

    @classmethod
    def sub(cls, text: str, replacements: list[tuple[str, str]]) -> str:
        """
        Applies Click styles to specific substrings within a larger text block
        (like an ASCII tree structure).

        This is highly useful for applying consistent styling to fixed characters
        (like tree lines: ├───, └───, │) without relying on complex regex.

        :param text: The original text block.
        :type text: str
        :param replacements: A list of tuples, where each tuple contains:
                             (substring, color)
        :type replacements: List[Tuple[str, str]]
        :returns: The modified text with styles applied.
        :rtype: str

        Example
        -------
        .. code-block:: python

            tree_text = "The letter 'Y' is repeated 4 times: Y Y Y Y"

            styled_text = ClickStyled.sub(
                tree_text,
                [
                    ("letter", "yellow"),    # All 'letter' matches turn yellow.
                    ("Y", "blue+"),          # All 'Y' matches turn bright_blue.
                ]
            )
        """

        for original, color in replacements:
            modifier = cls._apply_modifiers(color)

            styled_replacement = click.style(original, fg=modifier.color, bold=modifier.is_bold)

            text = text.replace(original, styled_replacement)

        return text


def echo(msg: str) -> None:
    """
    Convenience function that calls ClickStyled.echo()
    to print a message with inline style markup.

    The supported color names are the same as those in :func:`click.style`:

    * ``black`` (might be a gray)
    * ``red``
    * ``green``
    * ``yellow`` (might be an orange)
    * ``blue``
    * ``magenta``
    * ``cyan``
    * ``white`` (might be light gray)
    * ``bright_black``
    * ``bright_red``
    * ``bright_green``
    * ``bright_yellow``
    * ``bright_blue``
    * ``bright_magenta``
    * ``bright_cyan``
    * ``bright_white``
    * ``reset`` (only resets the color code)

    :param msg: The message to print, potentially containing style markers
                (e.g., "[red](Error: ...)").
    :type msg: str
    :returns: None
    :rtype: None

    Examples
    --------
    .. code-block:: python
        echo("[green](Success): Operation completed.")
        echo("[red!](Error): Critical failure.")
        echo("[yellow+](Warning): Check your config.")
    """
    full_message: str = ClickStyled.process(msg)
    click.echo(full_message)


def click_confirm(text: str, default: bool) -> bool:
    full_message = ClickStyled.process(text)
    return click.confirm(full_message, default)
